### ISSUE TITLE
chefspec fails due to missing webrick

### ISSUE THREAD

**Issue by y0y0z** [chefspec/chefspec#1000]
i am using chefspec since the it first appearance. lately, i've updated my code base and found out that i am unable to run chefspec

```shell
$ bundle exec rspec
....
Failure/Error: require "webrick" unless defined?(WEBrick)
```

which appears at [chef-zero|https://github.com/chef/chef-zero/blob/11834dc46868ebb6f3c84659c15822583b3cfd44/lib/chef_zero/server.rb#L26]

i am using the following chef et el versions with ruby version 3.

```shell
$ bundle list | grep chef
  * chef (16.8.14)
  * chef-cli (3.0.33)
  * chef-config (16.8.14)
  * chef-telemetry (1.0.14)
  * chef-utils (16.8.14)
  * chef-vault (4.1.0)
  * chef-zero (15.0.3)
  * chefspec (9.2.1)

$ bundle exec ruby --version
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]
```

is it ruby 3 compatibility issue or is it a bug in chef-zero that affects chefspec?

**Comment by tas50** [comment]
This is fixed with the updated chef-zero and I've pulled that into Chef Workstation for release in the next few days

**Comment by y0y0z** [comment]
@tas50: just updated my gems and the issue resolved.
