### ISSUE TITLE
install_package broken for windows paths

### ISSUE THREAD

**Issue by rylarson** [chefspec/chefspec#665]
Given a Windows platform (I tried 2008R2, 2008, and 2012), attempting to use the install_package matcher is broken if using a Windows Path with a specific source. The match always fails because at some point during the run or the match, the current working directory gets prepended to the actual value passed into source. Example:

``` ruby
# Recipe under test
package 'chocolatey' do
  source 'C:/chocolatey.msi'
  action :install
end
```

``` ruby
# ChefSpec test
subject do
  ChefSpec::SoloRunner.new(:platform => 'windows', :version => '2012').converge(described_recipe)
end

it { is_expected.to install_package('chocolatey').with_source('C:/chocolatey.msi') }
```

**Comment by sethvargo** [comment]
Hrm this is rather strange. Unfortunately I don't have handy access to a Windows machine at the moment, so I don't know how to start debugging this :frowning:

**Comment by lamont-granquist** [comment]
this is ultimately a dup of #652 since windows_package has a coercion on the source property:

```
      property :source, String,
                coerce: (proc do |s|
                  unless s.nil?
                    uri_scheme?(s) ? s : Chef::Util::PathHelper.canonical_path(s, false)
                  end
                end)
```
