### ISSUE TITLE
reliance on load-time configuration modification

### ISSUE THREAD

**Issue by ThisGuyCodes** [chefspec/chefspec#767]
[I've](https://github.com/sethvargo/chefspec/blob/72f766fc858dfa01dfc07e7b672c1dd3cb0a787c/lib/chefspec/rspec.rb#L1) [noticed](https://github.com/sethvargo/chefspec/blob/72f766fc858dfa01dfc07e7b672c1dd3cb0a787c/lib/chefspec/berkshelf.rb#L60) a [couple](https://github.com/sethvargo/chefspec/blob/72f766fc858dfa01dfc07e7b672c1dd3cb0a787c/lib/chefspec/librarian.rb#L47) [of](https://github.com/sethvargo/chefspec/blob/72f766fc858dfa01dfc07e7b672c1dd3cb0a787c/lib/chefspec/policyfile.rb#L59) [places](https://github.com/sethvargo/chefspec/blob/72f766fc858dfa01dfc07e7b672c1dd3cb0a787c/lib/chefspec/cacher.rb#L62) that modify the global `RSpec.configuration` object at load time, and at least [one place](https://github.com/sethvargo/chefspec/blob/72f766fc858dfa01dfc07e7b672c1dd3cb0a787c/lib/chefspec/solo_runner.rb#L305) that explicitly depends on that modified state being present at run time (though a lot of the other stuff is setup/cleanup so I imagine there are other ways those are depended on as well).

This presents a problem: load time only happens once.

I'm trying to create a tool requires I "codify" our running of RSpec, in particular it needs to run RSpec multiple times in an isolated manner; RSpec provides the ability to pass in your own configuration objects (which it'll then use instead of the default global one... mostly, though tests set their own configuration this way so it also provides a `RSpec#reset`), however because chefspec runners depend on this load-time modification of configuration, and said configuration gets deleted/reset between runs (because any test might set their own RSpec options, and I don't want those bleeding between runs), the second run doesn't have these modifications.

I acknowledge that stuff like the before and after hooks rely on this load-time behavior for features (this is why using berkshelf only requires adding `require 'chefspec/berkshelf` to your test files).

To wit I propose (and will attempt to implement if desirable) two ideas (and am looking for reasons they wouldn't work):
1. Move [some of the config](https://github.com/sethvargo/chefspec/blob/72f766fc858dfa01dfc07e7b672c1dd3cb0a787c/lib/chefspec/rspec.rb#L1) into the [runner initializer](https://github.com/sethvargo/chefspec/blob/72f766fc858dfa01dfc07e7b672c1dd3cb0a787c/lib/chefspec/solo_runner.rb#L64), that way it runs whenever a runner is created instead of just on library load.
2. Move load logic akin to [this](https://github.com/sethvargo/chefspec/blob/72f766fc858dfa01dfc07e7b672c1dd3cb0a787c/lib/chefspec/berkshelf.rb#L60) into their own methods, and (maybe?) start suggesting people use these methods instead of simply requiring, this would make it two lines of code instead of one /shrug (to preserve backwards compatibility this would still have to be run at load time).

Alternatively: is there another solution here?

**Comment by lamont-granquist** [comment]
my guess is that we're not opposed to merging patches that would fix this, but this is low enough priority we will never fix it.  it would likely be better to invoke rspec multiple different times with different rspec config values.
