### ISSUE TITLE
NoMethodError:  undefined method `[]=' for nil:NilClass

### ISSUE THREAD

**Issue by daytonpa** [chefspec/chefspec#781]
I am attempting to run ChefSpec, but I am consistently getting errors.  I have been following the documentation, but ChefSpec doesn't seem to like my syntax.
`
context 'when converging with default attributes' do

        let(:chef_run) do
            ChefSpec::SoloRunner.new do |node|
                # Default attributes
                node['appdynamics']{
                    'node-name' => 'subscribe-redhat-72'
                }
            end.converge('appdynamics::default')
        end

        it 'converges successfully' do
            expect{ chef_run }.to_not raise_error
        end
`

**Comment by chazzly** [comment]
I believe you need to set the precedence of the attribute:

> 

    let(:chef_run) do
        ChefSpec::SoloRunner.new do |node|
            # Default attributes
            node.normal['appdynamics'] = {
                'node-name' => 'subscribe-redhat-72'
            }

**Comment by lamont-granquist** [comment]
@tas50 this isn't a bug
