### ISSUE TITLE
Support multiple policies

### ISSUE THREAD

**Issue by kamaradclimber** [chefspec/chefspec#801]
At the moment, chefspec assumes tested policy is always described in `Policyfile.rb` at the root of the repository.

Some repositories might have multiple policies (for instance contained into a policies directory).

It would be convenient to be able to support specifying which policy needs to be run.

**Comment by kamaradclimber** [comment]
Ideally, I'd like to write:
```ruby
require 'spec_helper'

describe 'minimal' do
  context 'When all attributes are default, on centos' do
    let(:chef_run) do
      runner = ChefSpec::ServerRunner.new(
        platform: 'centos',
        version: '7.2.1511',
      )
      runner.converge_policy(policy_name: described_policy, policy_group: 'default')
    end

    it 'converges correctly' do
      expect { chef_run }.to_not raise_error
    end
  end
end
```

**Comment by coderanger** [comment]
This will not be supported. The use of policyfiles is purely for fetching dependencies, they are not a thing that it makes sense to unit test directly.

**Comment by kamaradclimber** [comment]
Thanks for the answer
