### ISSUE TITLE
how to mock multiple versions in different platforms?

### ISSUE THREAD

**Issue by vijaypatnana** [chefspec/chefspec#844]
Hi Community,

I want to test my cookbooks in different platforms and versions, but I didn't find anything related to this from documentation. I would appreciate if anyone comes with good example. Thank you!

**Comment by coderanger** [comment]
The platform and platform version are [configuration inputs documented in the README](https://github.com/sethvargo/chefspec#configuration). You can find the full list of platforms and versions supported by Fauxhai in that repo.
