### ISSUE TITLE
Chefspec error with file resource

### ISSUE THREAD

**Issue by pariminaresh** [chefspec/chefspec#846]
Scenario:
----------------
I have declared a file resource like below in my default recipe:
 
file "/java/lib/security/cacerts" do
  content IO.read("/app/cacerts")
  mode '0640'
  action :create
end

I have simple Chespec for the above piece of resource as following:

describe 'jnj_weblogic::default' do
  context 'When all attributes are default, on an unspecified platform' do
    let(:chef_run) do
      ChefSpec::SoloRunner.new(platform: 'centos', version: '7.3.1611') do |node|
        node.override['id'] = 'abcd'
      end.converge(described_recipe)
    end

     it 'converges successfully' do
       expect { chef_run }.to_not raise_error
    end
  end
end

Error Stack:
----------------
F

Failures:

  1) jnj_weblogic::default When all attributes are default, on an unspecified platform group and user creation piece
     Failure/Error:
       ChefSpec::SoloRunner.new(platform: 'centos', version: '7.3.1611') do |node|
          node.override['id'] = 'abcd'
       end.converge(described_recipe)
     Errno::ENOENT:
       No such file or directory @ rb_sysopen - /my/cacerts
     /tmp/d20170516-18360-1fzs6j8/cookbooks/jnj_weblogic/recipes/default.rb:60:in `read'
     /tmp/d20170516-18360-1fzs6j8/cookbooks/jnj_weblogic/recipes/default.rb:60:in `block in from_file'
     /tmp/d20170516-18360-1fzs6j8/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/dsl/declare_resource.rb:308:in `build_resource'

Expected outcome:
--------------------------
I'm expecting as it shouldn't throw any error as the default recipe has a single file resource and should converge without any issues.

Please make me to understand what's wrong here.

**Comment by pariminaresh** [comment]
It forced me to handle resource declaration in the below manner:

  begin
      content File.read("#{node['jnj_weblogic']['wlsSoftwareStaging']}/cacerts")
    rescue
      Chef::Log.warn "File Not Found: #{node['jnj_weblogic']['wlsSoftwareStaging']}/cacert"
    end

file "/java/lib/security/cacerts" do
  begin
     content IO.read("/app/cacerts")
   rescue
     Chef::Log.warn "File Not Found: /app/cacerts"
   end
  mode '0640'
  action :create
end

Declaring this way solves the problem for me. Is it how we need to wrap any arbitrary ruby code in recipe? Suggest me the right approach. Thanks

**Comment by joerg** [comment]
Hi,

You should stub the IO.read call as explained here: http://jtimberman.housepub.org/blog/2015/05/30/quick-tip-stubbing-library-helpers-in-chefspec/ (this is linked in the README). Otherwise this Ruby code is executed on your system and thus fails.

**Comment by pariminaresh** [comment]
Thanks @joerg. 
I tried giving like:
    before do
        allow_any_instance_of(Chef::Recipe).to receive(IO.read).and_return('')
    end

But It says 'ArgumentError: wrong number of arguments (0 for 1..4)'. Can you correct me if the declaration is wrong?

**Comment by joerg** [comment]
Google and the RSpec docs have plenty of examples for this, but there you go:

```
before do
  allow_any_instance_of(IO).to receive(:read).and_call_original
  allow_any_instance_of(IO).to receive(:read).with('/app/cacerts').and_return('my fake file content')
end
```

**Comment by lamont-granquist** [comment]
^ that looks very much like the correct answer to this question.
