### ISSUE TITLE
step_into custom resource_name does not work as expected

### ISSUE THREAD

**Issue by bharathcp** [chefspec/chefspec#848]
I have a custom resource with "resource_name" defined as `resource_name :xresource_install`. This is defined in `cookbook/resources/install.rb`
if I define chef_run as:
`ChefSpec::ServerRunner.new(step_into: 'xresource_install').converge(described_recipe)`
I get the below error:
```
Failure/Error:
       ChefSpec::ServerRunner.new(step_into: 'xresource_install').converge(described_recipe)

     Chef::Exceptions::NoSuchResourceType:
       xresource_install[something] (cookbook::default line 6) had an error: Chef::Exceptions::NoSuchResourceType: Cannot find a resource for user on chefspec version 0.6.1
```
If i change the chef_run definition to:
`ChefSpec::ServerRunner.new(step_into: 'cookbook_install').converge(described_recipe)`
everything works like a charm.

Obviously I would expect the step_into attribute to respect resource_name if defined in the custom resource instead of always assuming the default convention of `cookbook_resourcefilename`

**Comment by coderanger** [comment]
That shows it is actually working, but you use the `user` resource in your custom resource, which is not available on the default `chefspec` platform. You want to pick a platform to simulate like `ChefSpec::ServerRunner.new(step_into: 'xresource_install', platform: 'ubuntu', version: '16.04')` or similar. You can find the full list of platforms and versions available in https://github.com/customink/fauxhai/blob/master/PLATFORMS.md

**Comment by bharathcp** [comment]
Thank you. I have defined the platform now. But I am still struggling with the step_into. The test run acts as though it is not stepping into the custom_resource. 


```ruby
  let(:chef_run) do
      ChefSpec::ServerRunner.new(step_into: ['xresource_install'], platform: 'ubuntu', version: '16.04') do |node, server|
        node.set['java']['java_home'] = '/usr/lib/jvm/java-8-oracl'
        server.update_node(node)
      end.converge(described_recipe)
    end

    it 'converges successfully' do
      expect { chef_run }.to_not raise_error
      expect(chef_run).to install_xresource('xresource').with_jre_home('/usr/lib/jvm/java-8-oracl/jre')
      expect(chef_run).to create_directory('install_path')
    end
```
Expected: the test should pass as there is a create directory resource definition in custom resource - xresource_install 
Actual:I get an error - 
```
expected "directory[install_path]" with action :create to be in Chef run. Other directory resources:

```
Am I missing something?

**Comment by bharathcp** [comment]
I think I figured out the problem. I am using a wrong naming convention. Its all there in the examples. You guys are awesome.
