### ISSUE TITLE
Core Chef resources matchers are missing when chef is loaded before chefspec

### ISSUE THREAD

**Issue by Annih** [chefspec/chefspec#849]
Hello,

## Context 
I recently encountered a weird issue with ChefSpec 7.1.0 ... the `create_file` matcher was missing.
After 2 minutes of investigation I discovered 2 things:
* you guys introduced the new awesome feature of automatic matchers! :+1: 
* all Core Chef matchers are missing :cry: 

After 5 more minutes of investigation I found out that:
* the `automatic matchers` feature is based on a small monkey patch of the `::Chef::Resource` class
* I was requiring `chef` before `chefspec`

Removing the `require 'chef'` fixed my issue, but I think he would be smart to reinject matchers based on loaded resources. What do you think?

--------

## How to reproduce
```ruby
require 'chef'
require 'chefspec'

describe 'windows::default' do
  let(:chef_run) do
    ::ChefSpec::SoloRunner.new(platform:  'centos', version: '6.8') .converge(described_recipe)
  end

  it 'creates file' do
    expect(chef_run).not_to create_file(probation_file)
  end
end
```

Regards and bravo for the automatic matchers :)

**Comment by tas50** [comment]
That'll certainly break things, but there shouldn't be an actual need to require chef in your chefspecs. Is there a reason you're doing that?

**Comment by Annih** [comment]
No real one, that's why I removed it :)

I created this issue to save a few minutes to people who are in the same situation, and maybe improve the system if it needs to be improved.

**Comment by tas50** [comment]
I'm going to close this out since we won't be fixing it, but I'm sure it'll help at least one person in the future with their google searching

**Comment by Annih** [comment]
Ok no problem :)
