### ISSUE TITLE
How to match for dpkg_autostart

### ISSUE THREAD

**Issue by quulah** [chefspec/chefspec#851]
I have a [dpkg_autostart](https://github.com/hw-cookbooks/dpkg_autostart) resource in my recipe and would like to test for it.

I created the following matcher in support/matchers.rb and have it required in my spec_helper.
```
if defined?(ChefSpec)
  ChefSpec.define_matcher(:create_dpkg_autostart)

  def create_dpkg_autostart(resource_name)
    ChefSpec::Matchers::ResourceMatcher.new(:dpkg_autostart, :create, resource_name)
  end
end
```

Here's the spec:
```
it 'should disable dpkg autostart' do
  expect(chef_run).to create_dpkg_autostart('bin_file')
  expect(chef_run).to create_dpkg_autostart('snmpd')
end
```

Which results in ChefSpec finding the resources, but not quite properly:
```
     Failure/Error: expect(chef_run).to create_dpkg_autostart('bin_file')

       expected "dpkg_autostart[bin_file]" with action :create to be in Chef run. Other dpkg_autostart resources:

         dpkg_autostart[bin_file]
         dpkg_autostart[snmpd]
```
I also tried 7.1.0 with the automatic matcher feature, but that resulted in:
```
NoMethodError:
       undefined method `create_dpkg_autostart'
```

There's also the dpkg_autostart[bin_file] resource that pops up due to [this](https://github.com/hw-cookbooks/dpkg_autostart/blob/master/libraries/resource.rb#L24). Is there a way to skip it in my specs?

**Comment by szymonpk** [comment]
If you do not require `support/matchers.rb` explicitly it will not work. You can put this file in `libraries` in your cookbook.

I can confirm 7.1 automated matchers does not detect create action but it works with `exepect(chef_run).to nothing_dpkg_autostart("foo")`.

**Comment by quulah** [comment]
Yes, I had the matchers.rb required and I have other working matchers. I don't think that's the problem.

I'll have to take a closer look at the automatic matchers at some point, but just throwing the nothing action in the spec didn't seem to help either.

Since there's so little discussion in this issue, I'll close this any way.
