### ISSUE TITLE
How do I test that no resources have been created?

### ISSUE THREAD

**Issue by Poohblah** [chefspec/chefspec#853]
I'm writing a recipe that runs a search against the Chef server to find other members of the cluster and add those nodes to the configuration via a resource call (let's call the resource `cluster_member`).  In my chefspec tests, I would like to test the case that the search returns no results, in which case no `cluster_member` resources should be called.  How can I test that **no** `cluster_member` resources have been created?  I'm thinking something along the lines of:

```
expect(chef_run).to_not create_cluster_member.with_any_name
```
or
```
expect(chef_run).to_not create_cluster_member(/.*/)
```

It looks to me like the second version works, but I'm not sure whether that's a) actually true or just true in the limited cases that I've tested so far, or b) by design or by sheer coincidence.  I'm looking for a canonical answer to this question, since the docs don't appear to touch on this particular use case.

**Comment by lamont-granquist** [comment]
this question is not a bug report and should be directed towards slack, stackoverflow or discourse.

**Comment by Poohblah** [comment]
A couple questions:

1. I don't see the Slack channel or Discourse channel in the [readme](https://github.com/chefspec/chefspec/blob/master/README.md) or [contributing guidelines](https://github.com/chefspec/chefspec/blob/master/CONTRIBUTING.md).  If you want people to ask questions in those forums, perhaps that information should be added to one of those places?
2. If I were to rephrase this issue as "could we please have the answer to my question added to the chefspec docs", would that count as a bug report suitable for GitHub issues?
