### ISSUE TITLE
how can i make coverage report to be saved as a file

### ISSUE THREAD

**Issue by bharathcp** [chefspec/chefspec#854]
The [blog](https://sethvargo.com/chef-recipe-code-coverage/) says a report is created by default - `.coverage/results.json`.

I do not see any report created using the latest chefspec gem. Am I to set some option to generate a report file or should I resort to reading output from the log?

**Comment by coderanger** [comment]
We no longer generate a JSON file by default however you can see an example of how to set it up yourself in whatever format you want in https://github.com/chefspec/chefspec#reporting.

More generally, ChefSpec coverage reporting is generally unproductive and we don't recommend you use it in most cases.

**Comment by bharathcp** [comment]
cool. i suppose you are right.
