### ISSUE TITLE
testing same resource being called twice in a recipe

### ISSUE THREAD

**Issue by bharathcp** [chefspec/chefspec#855]
I have a scenario where I create a directory with root user, then create a new user to use that directory has home path. Then I change the directory ownership to the new user. Code snippet is:
```
  directory new_resource.home_path do
    owner 'root'
    group 'root'
    mode 00755
    action :create
    recursive true
    not_if { ::Dir.exist?(new_resource.home_path) }
  end

  group new_resource.some_group do
    action :create
    append true
  end

  user new_resource.some_user do
    gid new_resource.some_group
    comment 'some Service Account'
    home new_resource.home_path
    shell '/bin/bash'
    manage_home true
    system true
    action :create
  end

  # changing ownership after user creation
  directory new_resource.home_path do
    owner new_resource.some_user
    group new_resource.some_group
    mode 00755
    action :create
    recursive true
  end
```
In this case I am able to easily test the directory resource call with 'some_user' ownership. But I am not able to test the initial directory resource call with root user.  If i test using - 
```
      expect(chef_run).to create_directory('home_path').with_user('root').with_mode(00755)
```
it gives an error saying - `user "root", was "atlbitbucket"`

Let me know if there is a way to test this type of sequence?

**Comment by coderanger** [comment]
Not really, nor should you have code like this in the first place. There is no need to create the user's homedir before the user is made. Just do it afterwards.

**Comment by bharathcp** [comment]
thank you for that. Agreed 👍

**Comment by coderanger** [comment]
If it comes up in another case in the future you can either change the name of one of the two resources or scan through the resource collection more manually. Not impossible, but not easy :)
