### ISSUE TITLE
Caused by Chef::Exceptions::CookbookNotFound

### ISSUE THREAD

**Issue by pkara2** [chefspec/chefspec#856]
Hi Team, 
We are trying to deploy a template over our organisation Dev cloud, and that template will be used to create instances later and once some one spin up instance using that template  a email should be triggered to that person email id with credential and IP.

we are using vapputil tbuild  to build template from our cookbooks,  we have berkfile configured. 
Problem:- When we are trying to build template although it is building fine but it's not triggering mail  to user with credential, when we tried to login to instance with default password. it is showing below error in /var/nodeinit/chef/chef/cache.

**Chef::Exceptions::CookbookNotFound: Cookbook mc_aem_author not found. If you're loading mc_aem_author from another cookbook, make sure you configure the dependency in your metadata
[2017-06-19T09:43:39-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
20170619-09:43:39: chefrun: ERROR: Chef Solo command failed with exit code: 1.**

mc_aem_author is our cookbook and it is building template fine but no email triggered with above error on instance

Attached is the error file.

Please help and guide in above issue.
Thanks in Advance
Regards,
Pratibha Karakoti
[error.txt](https://github.com/chefspec/chefspec/files/1091338/error.txt)

**Comment by lamont-granquist** [comment]
this does not look like a chefspec bug
