### ISSUE TITLE
'It' block automated naming broken after 7.x upgrade

### ISSUE THREAD

**Issue by szymonpk** [chefspec/chefspec#859]
After upgrading to 7.x I have noticed ChefSpec behavior change in automated naming for it blocks. It is ground breaking, but it was 'neat' feature.

For the code:

```
directory "/var/spool/foo" do
  mode "0700"
end
```

And the test:

```
it do
  expect(chef_run).to create_directory("/var/spool/foo").with(mode: "0700")
end
```

Output of `rspec my_spec.rb -f doc` was (before 7.x): `should create directory "/var/spool/foo"`. Currently it is `should  directory "/var/spool/foo"` - action is missing (two spaces).

**Comment by rmoriz** [comment]
I have the same issue when using the http://www.betterspecs.org/ way of testing, especially when nesting:

```ruby
describe 'cookbook::recipe' do
  cached(:chef_run) { ChefSpec::ServerRunner.new.converge(described_recipe) }
  subject { chef_run }

  it {
    # - LSB release
    is_expected.to install_package 'lsb-release'

    # - Cloud-init removal
    is_expected.to remove_package 'cloud-init'

    # - Hostname
    is_expected.to include_recipe 'hostname::default'

...
}
```

Usually I don't get any output from that or only the last expectation.

**Comment by lamont-granquist** [comment]
I can't replicate this on rspec 3.7.x and chefspec 7.2.1

As this looks like pure rspec functionality, it was probably a bug in an old version of rspec
