### ISSUE TITLE
stubbing libraries return value

### ISSUE THREAD

**Issue by y0y0z** [chefspec/chefspec#860]
although i came across few other issues ([549](https://github.com/chefspec/chefspec/issues/549), [562](https://github.com/chefspec/chefspec/issues/562
), [601](https://github.com/chefspec/chefspec/issues/601)), yet i was unable to find any working solution (or bypass).

i am including other [openssl cookbook](https://github.com/chef-cookbooks/openssl) library in my recipe and wish to test it with chefspec. following is a snippet of how i try to do it:

```bash
$ cat recipes/default.rb
Chef::Recipe.send :include, OpenSSLCookbook::RandomPassword
password = random_password length: 32, mode: :base64, encoding: 'ASCII'

template '/tmp/tmpl' do
  # some parameters left out
  variables(password: password)
end

$ cat spec/recipes/default_spec.rb
require 'spec_helper'
require_relative '../../../openssl/libraries/random_password.rb'

describe 'foobook::default' do
  before do
    allow_any_instance_of(OpenSSLCookbook::RandomPassword).to receive(:random_password).and_return('')
  end

  cached(:chef_run) { do_convergence }

  it 'generates template' do
    expect(chef_run).to create_template('/tmp/tmpl')
      .with(variables: { password: '' })
  end
end
```

when i ran chefspec, i get the following error:

```bash
expected "template[/tmp/tmpl]" to have parameters:
password "", was "OMJhO/3xWbU27UgvYapeDfyMkfrYxNNw"
```

when i drop the `require_relative '../../../openssl/libraries/random_password.rb'` from `spec/recipes/default_spec.rb`, i get the following error when running chefspec:

```bash
uninitialized constant OpenSSLCookbook
```

also tried to modify the `before` block as follows:
```bash
before do
  allow_any_instance_of(Chef::Recipe).to receive(:random_password).and_call_original
  allow_any_instance_of(Chef::Recipe).to receive(:random_password).with(any_args).and_return('')
end
```
i get the following error when running chefspec:
```bash
Chef::Recipe does not implement #random_password
```

could anyone please direct me explicitly how to test my recipe correctly, that is -- how to stub the return value of the `random_password` function?

**Comment by lamont-granquist** [comment]
`allow_any_instance_of(Chef::Recipe).to receive(:random_password).and_return('')` should have worked.

**Comment by lamont-granquist** [comment]
again i'm going to close this one as not really a bug report and more of a how-do-i-rspec question that would be better sent to discourse, stackoverflow or slack.
