### ISSUE TITLE
Add config for Chef::Client's json_attr for SoloRunner

### ISSUE THREAD

**Issue by twk3** [chefspec/chefspec#861]
We already have several ways of overriding attributes that may be expected to have been set this way through the faux path config, or directly on the node when we create the runner using the block etc. 

But if if you are trying to build out a test for chef-solo run that normally uses the ```-j/--json-attributes flag``` for some config, it would be cleaner in the tests if we could set this and have it passed to Chef::Client.new

Request may be somewhat related to: https://github.com/chefspec/chefspec/issues/560

**Comment by coderanger** [comment]
Not sure what you're asking for, the way you set node attributes for testing is via the constructor.

**Comment by twk3** [comment]
This is more of a nice-to-have for solo runner configs. I realise you *can* already set the node attributes several other ways.

chefspec lets you specify the roles, environments, and data_bags paths already, but chef solo also has this idea of a json config file you can pass in. This file may already exist in your cookbooks path, and it would be a nice addition to be able to parse one of these and pass it into `Chef::Client.new` if it has been specified as a rspec config option for chefspec.

So this is for the scenario where you are not only using solorunner for testing, but  chef-solo is actually what normally runs the cookbooks you are testing. In my case, this is a chef omnibus-ctl setup.

**Comment by coderanger** [comment]
That's not what unit testing is for, check out things like rspec-command (disclaimer: mine) or ariba.

**Comment by twk3** [comment]
I am not testing the omnibus-ctl command, but the cookbooks it uses during it's chef-solo run. 

It's just a scenario where there is never any nodes/roles/environments folders, but a single json file passed into `chef-client -z -c {solo_config_file.rb} -j {attributes_file.json}`

It would be nice to provide this option in chefspec as well.

The current way to do this is pretty easy:

```
ChefSpec::SoloRunner.new do |node|
  node['attribute'] = 'blah'
  ...
end.converge(described_recipe)
```

But it would be nice to be able to do:

```
RSpec.configure do |config|
  config.json_attributes = 'files/cookbooks/dna.json'
end
```

and
```
ChefSpec::SoloRunner.new(json_attributes: 'spec/fixtures/dna.json').converge(described_recipe)
```

**Comment by coderanger** [comment]
`node.normal.update(JSON.parse(IO.read('whatever')))` is probably what you're looking for, but we discourage use of the normal level in general. That includes `chef-solo -j`.

**Comment by lamont-granquist** [comment]
Yeah, I don't think this should be encouraged via formal APIs, and the one-liner will work fine.
