### ISSUE TITLE
Slow Tests

### ISSUE THREAD

**Issue by willis7** [chefspec/chefspec#862]
As a new user of Chef Spec, one of my first observations was how slow running unit tests are. I appreciate these are an order of magnitude faster than Inspec, and so I'm keen to persevere.

The following spec took 14 seconds to run:

``` ruby
require 'spec_helper'

describe 'dashboard::cron' do
  context 'When all attributes are default, on debian 8.7' do
    let(:chef_run) { ChefSpec::ServerRunner.new(DEBIAN_OPTS).converge(described_recipe) }

    it 'converges successfully' do
      expect { chef_run }.to_not raise_error
    end

    it 'creates a cron with attributes' do
      expect(chef_run).to create_cron('weather_data').with(
        minute: '15',
        user: 'deployer',
        home: '/home/deployer'
      )
    end
  end
end
```

Is there anything I can do to speed this up, or should I accept this constraint?

**Comment by coderanger** [comment]
Switch to SoloRunner, it will be faster.

**Comment by willis7** [comment]
Given this isn't the default with `chef generate`, I'm guessing the usage of SoloRunner comes at a cost? Can you advise further?

**Comment by coderanger** [comment]
It does not, the default generators are incorrect however I no longer want to fight that battle with Chef Software so I've left them to their own devices. The deeper issue is that SoloRunner uses the old solo codepaths which are slated for removal in 2018, however this will only happen if the new code (i.e. ServerRunner) can be made not slow. At some future point the goal is that both will use the same underlying code and it will just be `ChefSpec::Runner`, but that day is not today so use SoloRunner.

**Comment by coderanger** [comment]
The other thing to speed up tests is to combine examples. So if you do:

```ruby
subject { ChefSpec::SoloRunner.converge(described_recipe) }
it { is_expected.to install_package('whatever') }
it { is_expected.to create_cron('weather_data') }
```

that would run Chef twice, once for each example using the runner object. You can combine them to run Chef only once:

```ruby
subject { ChefSpec::SoloRunner.converge(described_recipe) }
it do 
  is_expected.to install_package('whatever')
  is_expected.to create_cron('weather_data')
end
```

this means slightly less test isolation but since there shouldn't be any cross talk between those two examples, this is not usually a problem.

**Comment by coderanger** [comment]
Going to close this out as there is no specific bug to be fixed.

**Comment by willis7** [comment]
Thank you, your knowledge was valuable and I did manage to speed up the tests with SoloRunner.

Good luck with this.
