### ISSUE TITLE
Berkshelf / Librarian support should preserve configured cookbook_path via array of paths

### ISSUE THREAD

**Issue by andyfeller** [chefspec/chefspec#866]
The current dependency manager support (i.e. Berkshelf and Librarian) assumes cookbooks either reside locally or within the dependency manager when it's possible / probable to do both.  To this end, [chefspec/lib/chefspec/berkshelf.rb](https://github.com/chefspec/chefspec/blob/master/lib/chefspec/berkshelf.rb#L48) and [chefspec/lib/chefspec/librarian.rb](https://github.com/chefspec/chefspec/blob/master/lib/chefspec/librarian.rb#L32) should preserve the existing cookbook_path configuration by assigning the option an array of directories as needed.

**Comment by coderanger** [comment]
No, you would handle this entirely within the Berksfile or Cheffile if you are going down that path.

**Comment by coderanger** [comment]
With recent-ish Berks, that can be handled via `source chef_repo: 'path/to/cookbooks/'`.

**Comment by coderanger** [comment]
Going to close this out as we don't intend to change this at this time. Happy to walk you through more details of how to configure the Berksfile on Slack if you have questions.

**Comment by andyfeller** [comment]
Just to make a note that this feature was released in v6.1.0 of berkshelf.
