### ISSUE TITLE
Appears to be significantly slower with chef 13 than chef 12

### ISSUE THREAD

**Issue by acoulton** [chefspec/chefspec#870]
I'm updating a number of our wrapper cookbooks and finding that the chefspec run is significantly slower with chef 13 than chef 12.

For example see https://travis-ci.org/ingenerator/chef-ingenerator-php/builds/262688704 - total job time of 9 minutes with chef 12, compared to 21 minutes with chef 13. Internally, rspec took 17 minutes 24 seconds on the chef 13 job, 8 minutes 11 seconds with chef 12.

![image](https://user-images.githubusercontent.com/416566/29128256-41f955d4-7d1b-11e7-8c26-21742bd9240e.png)

I'm seeing the same discrepancy on all builds and on multiple cookbooks. The only difference between the two runs is the gemfile in use : one specifies chef 12 and the other specifies chef 13. Even the chef 12 build is about double what I was previously seeing with chefspec 5.4.0 and chef 12.

I have tried:
* verifying that I'm using `SoloRunner` rather than `ServerRunner`
* making sure that vendors etc are in a chefignore file
* setting `config.server_runner_clear_cookbooks = false`

Is this expected? Is there anything more I can do to reduce the runtime with Chef 13?

**Comment by coderanger** [comment]
Hmm, I can't really think of why it would be that much slower. I checked a few of my cookbooks and the one with the most specs is at about 5 seconds for Chef 12 vs 7 seconds for Chef 13, which is well within the realm of random timing nonsense. What are you even doing in your specs that they take multiple minutes in the first place?

**Comment by coderanger** [comment]
Something seems really fishy here, I just looked over your specs real quick and they look fine. The cookbook I mentioned before is running over 400 specs in under 10 seconds so 63 specs should definitely not be taking minutes. Does it also take minutes running locally for you?

**Comment by acoulton** [comment]
@coderanger wow, OK. I don't think it's quite so bad locally, but yes definitely well up into minutes (and always has been multiple minutes rather than seconds for me so I'd assumed that was expected 😳). Can you point me to one of your fast-spec cookbooks (I had a look at your github profile but couldn't spot one easily) and I'll see if I can figure out what I'm doing differently (wrong 😁 )

**Comment by acoulton** [comment]
I've done some more debugging and think I may have found a partial solution, at least for Chef 13. Berkshelf wasn't properly processing my chefignore patterns (per berkshelf/berkshelf#1492) in particular `vendor/*` so the cookbook under test was being uploaded with all the build-environment gems which will have been gumming things up no end.

[Adding the directory names without trailing `/*` to my chefignore](https://github.com/ingenerator/chef-ingenerator-php/pull/5) has cut the rspec execution time to 35 seconds with Chef 13, which is still slow by your standards but I can live with. For some reason that hasn't helped with Chef 12, which is still running at about 8 minutes - but we'll be retiring chef 12 support soon so I can probably live with that too.

**Comment by coderanger** [comment]
The one I was looking at is `poise/poise` but my code is hard to interpret since I have have very unique helper libraries. You're using the Berkshelf integration, which does add some overhead but it should only be once for the whole test run. Nothing should be getting uploaded anywhere if you're using SoloRunner so if that fixes things I'm kind of worried :P

**Comment by acoulton** [comment]
hm, curiouser and curiouser. I've just verified on another project : that chefignore change reduces the chef 13 build time from [6m21](https://travis-ci.org/ingenerator/chef-ingenerator-source/jobs/262750159) to [7.97 seconds](https://travis-ci.org/ingenerator/chef-ingenerator-source/jobs/262848058#L616) but the chef 12 time stays roughly the same. I'll have a look at `poise/poise` tomorrow.

**Comment by coderanger** [comment]
Okay, that's good to know even if I can't explain it yet :)

**Comment by acoulton** [comment]
With fresh eyes, I've spotted that the vendored build gems are in a different location on the travis chef 12 build (because the gemfile is in a different path) and that wasn't being chefignored. Adding that has consistently got all the builds into the few-seconds range.

So it's not a chef 12 / chef 13 issue at all, it appears to be purely related to the size / number of files in the cookbook and is the same on both versions. I'll have a little look to see if I can spot what's making it slow without the chefignore, though I'm no ruby specialist.

**Comment by acoulton** [comment]
@coderanger I have got to the bottom of this. The delay happens in [Chef::Cookbook::CookbookVersionLoader.load](https://github.com/chef/chef/blob/master/lib/chef/cookbook/cookbook_version_loader.rb#L59) and [Chef::Cookbook::CookbookVersionLoader.cookbook_version](https://github.com/chef/chef/blob/master/lib/chef/cookbook/cookbook_version_loader.rb#L96) and ultimately has the same root cause.

The load method iterates over the full directory tree within the cookbook to get a list of all the cookbook files, before then iterating over that list to reject any that are matched by the chefignore. The resulting filtered list is then held in memory, and subsequently copied to a new array of files that gets passed into the cookbook version object.

If the build gems are vendored into the cookbook directory (eg as on travis when using bundle install --deployment to provision them) then there are around 10,000 files in the `vendor` directory. The .git directory obviously also has another good chunk of files, etc.

* With no chefignore present, the `:all_files` hash ends up with all of these 10k entries, then this list is iterated to check individually for ignores, and then this full list is copied across to the version object. This combined takes a fairly consistent 7 seconds for every converge on my local machine.
* With a chefignore that has chef-style directory patterns, the result is the same : for reasons I don't understand the [cookbook loader loads a chefignore for the parent repo path, not the cookbook path](https://github.com/chef/chef/blob/master/lib/chef/cookbook_loader.rb#L168) so nothing is ignored. Changing this to use the cookbook path halves the runtime, as although the 10,000 files are found on the first pass they're then filtered out before the array is passed to the version object.
* With the extra `vendor` etc entries in the chefignore to meet the berkshelf requirement, those directories are all filtered out during berkshelf setup (which reduces that overhead from about 6.6 seconds to 34ms) and so then the chef run only ever finds the desired cookbook files and runs super-fast.

So for people using berkshelf, until berkshelf/berkshelf#1492 is fixed the solution is to make sure the chefignore specifies both `vendor` and `vendor/*`.

But the issue will still arise for anyone not using berkshelf, unless Chef changes the way it loads cookbook files to respect the chefignore and to pre-emptively filter directories rather than descending into them and post-filtering. I think the only way to avoid that as it stands is just to avoid bundling the gems into vendor in the first place. I don't think there's much you can do from Chefspec?

Perhaps it would be enough to just add a note about this in the README? If so I can propose something.

**Comment by lamont-granquist** [comment]
this has nothing to do directly with chefspec code so closing this here.

**Comment by acoulton** [comment]
Great, thanks @lamont-granquist

**Comment by lamont-granquist** [comment]
fixed via #903 as part of #905

**Comment by joelhandwell** [comment]
```
joel@JOEL-LAPTOP C:\Users\joel\code\oss\neo4j
> chef exec rspec
......

Finished in 11.43 seconds (files took 23.46 seconds to load)
6 examples, 0 failures

C:\WINDOWS\system32>cup chefdk -y
Chocolatey v0.10.11
Upgrading the following packages:
chefdk
By upgrading you accept licenses for the packages.

You have chefdk v3.0.36 installed. Version 3.1.0 is available based on your source(s).
Progress: Downloading chefdk 3.1.0... 100%

chefdk v3.1.0 [Approved]
chefdk package files upgrade completed. Performing other installation steps.
Downloading chefdk 64 bit
  from 'https://packages.chef.io/stable/windows/2012r2/chefdk-3.1.0-1-x64.msi'
Progress: 100% - Completed download of C:\Users\joel\AppData\Local\Temp\chocolatey\chefdk\3.1.0\chefdk-3.1.0-1-x64.msi (352.49 MB).
Download of chefdk-3.1.0-1-x64.msi (352.49 MB) completed.
Hashes match.
Installing chefdk...
chefdk has been installed.
  chefdk may be able to be automatically uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The upgrade of chefdk was successful.
  Software installed as 'MSI', install location is likely default.

Chocolatey upgraded 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Enjoy using Chocolatey? Explore more amazing features to take your
experience to the next level at
 https://chocolatey.org/compare

joel@JOEL-LAPTOP C:\Users\joel\code\oss\neo4j
> chef -v
Chef Development Kit Version: 3.1.0
chef-client version: 14.2.0
delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
berks version: 7.0.4
kitchen version: 1.22.0
inspec version: 2.1.72

joel@JOEL-LAPTOP C:\Users\joel\code\oss\neo4j
> chef exec rspec
......

Finished in 9.38 seconds (files took 26.94 seconds to load)
6 examples, 0 failures
```

On Windows, loading took more time but execution took less time after upgrading chefdk 3.1.0

**Comment by coderanger** [comment]
@joelhandwell The major improvements are not in ChefDK 3.1, or even in a released ChefSpec yet. You would have to dive in with Bundler to test them out for now.

**Comment by joelhandwell** [comment]
@coderanger Thanks. I saw 3.1.0 updated and saw this one merged almost at the same time, got so excited and forgot to check if this change was in 3.1 or not. Waiting for future release. Thank you for hard work!
