### ISSUE TITLE
ChefSpec should properly handle Cookbook's metadata's gems

### ISSUE THREAD

**Issue by Annih** [chefspec/chefspec#871]
Hello,

Using gem dependencies in a cookbook metadata introduce weird behavior in ChefSpec.
The Chef GemInstaller will perform some operations that might mess up with the environment (e.g. `bundle install`)
These impacts are not limited to the cookbook with the gem dependency but to all contingent cookbooks.

Don't you think ChefSpec should try to handle the `gem` statement smartly?
* When the gem is used inside resources/providers, because in 90% of the time ChefSpec does not execute action's code, the gem is not required.
* When the gem is used at compile time (attributes/libraries/recipes) ChefSpec, ChefSpec will need this gem to test the cookbook properly.

I suggest that ChefSpec overrides the GemInstaller behavior
* If the gem is available in the local bundler/Gempath it does nothing
* If the gem is not available it warns the user to put the gem in its Gemfile

What do you think?

I'll try to provide a PR soon with an implementation of my suggestion, but I needed this issue for tracking purpose :)

*Cc.* @aboten

**Comment by coderanger** [comment]
This is way out of scope for ChefSpec unfortunately. You need to install the required gem into the environment ChefSpec is running in.

**Comment by coderanger** [comment]
Also of note: using a Gemfile in combination with ChefDK is almost always a mistake, use `chef gem install`.

**Comment by Annih** [comment]
@coderanger what if I provide a PR , would it be accepted or at least considered?

I would be ok about adding the gem in a single cookbook environment, but when I have to update all cookbooks that depends on it... it starts to be painful.

About your note, why are you talking about Gemfile combination with ChefDK, who said I was using the ChefDK? :D

**Comment by coderanger** [comment]
I'm happy to review a PR but I really can't think of any way to implement this that would work well. I mentioned the ChefDK issue because while you might not be, many users are so any changes would have to work within those restrictions.

**Comment by Annih** [comment]
Do you agree that running ChefSpec shouldn't touch user's environment?

The same way that ChefSpec disable the `chef_gem` behavior`, I would like to disable the gem dependency behavior.
If the gem is really required to perform the test, the user will have to install it, that's why I would like to display a big warning explaining how to install the gem if it's missing from the ruby load path. 

Is there any equivalent to the `Gemfile` using the ChefDK?
The warning could describe the procedure for ChefDK, Bundler &  Gem.

Optionally we could add a flag to let ChefSpec perform the gem install.

I'll try to hack this tomorrow (French time)

**Comment by coderanger** [comment]
Yeah I agree it should probably get defanged somehow, I just don't see a great way as to how exactly.
