### ISSUE TITLE
CONNECTION REFUSED

### ISSUE THREAD

**Issue by williamcern17** [chefspec/chefspec#874]
I am trying to bootstrap a node:

i get this error 

Creating new client for william
Creating new node for william
Connecting to 10.1.1.20
root@10.1.1.20's password:
10.1.1.20 -----> Existing Chef installation detected
10.1.1.20 Starting the first Chef Client run...
10.1.1.20 Starting Chef Client, version 13.4.24
10.1.1.20 [2017-09-27T20:33:50+00:00] ERROR: Connection refused connecting to https://localhost/organizations/eti/nodes/william, retry 1/5
10.1.1.20 [2017-09-27T20:33:55+00:00] ERROR: Connection refused connecting to https://localhost/organizations/eti/nodes/william, retry 2/5
10.1.1.20 [2017-09-27T20:34:00+00:00] ERROR: Connection refused connecting to https://localhost/organizations/eti/nodes/william, retry 3/5
10.1.1.20 [2017-09-27T20:34:05+00:00] ERROR: Connection refused connecting to https://localhost/organizations/eti/nodes/william, retry 4/5
10.1.1.20 [2017-09-27T20:34:10+00:00] ERROR: Connection refused connecting to https://localhost/organizations/eti/nodes/william, retry 5/5
10.1.1.20
10.1.1.20 ================================================================================
10.1.1.20 Chef encountered an error attempting to load the node data for "william"
10.1.1.20 ================================================================================
10.1.1.20
10.1.1.20 Networking Error:
10.1.1.20 -----------------
10.1.1.20 Connection refused - Connection refused connecting to https://localhost/organizations/eti/nodes/william, giving up
10.1.1.20
10.1.1.20 Your chef_server_url may be misconfigured, or the network could be down.
10.1.1.20
10.1.1.20 Relevant Config Settings:
10.1.1.20 -------------------------
10.1.1.20 chef_server_url  "https://localhost/organizations/eti"
10.1.1.20
10.1.1.20 System Info:
10.1.1.20 ------------
10.1.1.20 chef_version=13.4.24
10.1.1.20 ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
10.1.1.20 program_name=chef-client worker: ppid=13287;start=20:33:49;
10.1.1.20 executable=/opt/chef/bin/chef-client
10.1.1.20
10.1.1.20
10.1.1.20 Running handlers:
10.1.1.20 [2017-09-27T20:34:15+00:00] ERROR: Running exception handlers
10.1.1.20 Running handlers complete
10.1.1.20 [2017-09-27T20:34:15+00:00] ERROR: Exception handlers complete
10.1.1.20 Chef Client failed. 0 resources updated in 26 seconds
10.1.1.20 [2017-09-27T20:34:15+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
10.1.1.20 [2017-09-27T20:34:15+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
10.1.1.20 [2017-09-27T20:34:15+00:00] ERROR: Connection refused - Connection refused connecting to https://localhost/organizations/eti/nodes/william, giving up
10.1.1.20 [2017-09-27T20:34:15+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

Can someone help please?!  Thanks in advance

**Comment by williamcern17** [comment]
after i run <knife ssl fetch> and then i run <knife ssl check>, 
 get this error:
Connecting to host localhost:443
ERROR: Network Error: Connection refused - connect(2) for "localhost" port 443
Check your knife configuration and network settings

Can someone help please?  Thanks in advance!

**Comment by Gustavodecker** [comment]
News? I'm also having this same problem. :/

**Comment by williamcern17** [comment]
Did you get this rectified?  There is a solution for this.  If you need
assistance, contact me on slack or link...

**Comment by coderanger** [comment]
I think you filed this in the wrong place. This is the ChefSpec project, a unit testing library for Chef. You can find Chef itself over at https://github.com/chef/chef.
