### ISSUE TITLE
test accumulator pattern

### ISSUE THREAD

**Issue by jacoelho** [chefspec/chefspec#877]
I am having some testing recipes using the "accumulator" pattern:

```
# recipe
template node["foo"]["config_file"] do
    source "foo.conf.erb"
    action :nothing
end

foo "test"
```

```
# resource
resource_name :foo
property :name, String, name_property: true, required: true
property :config_file, String, default: lazy { node['foo']['config_file'] }
property :cookbook, String, default: 'foo'

default_action :create

action :create do
  with_run_context :root do
    edit_resource(:template, config_file) do |new_resource|
      cookbook new_resource.cookbook
      variables[:config] ||= {}
      variables[:config][new_resource.name] = 'foo'
      action :nothing
      delayed_action :create
    end
  end
end
```

if I try to test using the regular chefspec snippet:

```
expect(chef_run).to render_file('/etc/foo').with_content { |content|
  expect(content).to match(/foo/)
}
```
chefspec doesn't detect the accumulated values.

Is there a way of testing a delayed render?

**Comment by lamont-granquist** [comment]
are you stepping into the resource properly because otherwise all you'll get is the `foo[test]` resource in your collection and the action code will never get run.

**Comment by damacus** [comment]
HAProxy uses this to test the accumulator pattern: 
https://github.com/sous-chefs/haproxy/blob/master/spec/unit/recipes/listen_spec.rb

and it's correctly picking up the accumulated values (the listen resource modifies a template created by install).

**Comment by lamont-granquist** [comment]
i'd strongly suggest testing accumulators with test-kitchen and not chefspec, but otherwise do it more or less that way.
