### ISSUE TITLE
Coverage Report Jenkins consumable format

### ISSUE THREAD

**Issue by dagezou** [chefspec/chefspec#879]
The existing coverage report is next to useless in CI environments.  Its format is independent of the rest of the rspec output and is simply tacked onto the end.  If you create html output, the coverage information is NOT rendered in html, just tacked onto the end of the report as plain text.  If you produce junit format, the coverage information is also not usable.

What is needed is the coverage report to be in a separate file and in a consumable format such as cobertura.

Unless there is a method I am missing of producing coverage information that Jenkins can use?

**Comment by dragon788** [comment]
You could add this yourself via SimpleCov, as chefspec is really just a set of rules for Rspec. Check out this handy page I may end up implementing for our CI system.

https://www.cakesolutions.net/teamblogs/brief-introduction-to-rspec-and-simplecov-for-ruby

**Comment by rreilly-edr** [comment]
@dragon788   did you set this up to use chefspec with simplecov ? I was not sure what to for the use with require_relative ...

**Comment by coderanger** [comment]
This is not a thing we can do. ChefSpec coverage reporting is not coverage in the sense of any other tool. Also the feature will likely be removed soon. Do not use it.
