### ISSUE TITLE
Notify with Parameter not working as expected.

### ISSUE THREAD

**Issue by MichaelStankiewicz** [chefspec/chefspec#880]
According to the examples for the [notification spec](https://github.com/chefspec/chefspec/blob/master/examples/notifications/spec/immediately_spec.rb), I should be able to test notifications thusly:

`expect(template).to notify('service[receiving_resource]').to(:restart).immediately`

My spec example is below.  This was working before, the only thing that I recall changing at all was that I upgraded to the Chef DK instance to version 2.3.4 from 2.3.1.

`expect(chef_run.dsc_resource('[WindowsFeature]feature')).to notify('reboot[Application_Requires_Reboot]').to(:reboot_now).immediately`

When I run this, I get the below error.  However, if I drop the _immediately_ property from the string, the spec works.  

> Failures:
> 
>   1) cookbook::recipe On server runs dsc_resource to install relevant Windows features
>      Failure/Error: expect(chef_run.dsc_resource('[WindowsFeature]feature')).to notify('reboot[Application_Requires_Reboot]').to(:reboot_now).immediately
> 
>        expected "dsc_resource[[WindowsFeature]feature]" to notify "reboot[Application_Requires_Reboot]" with action :reboot_now immediately, but did not.
> 
>        Other notifications were:

Note that the section below the last line of the error is blank.

The relevant recipe code corresponding to this spec test is:

```
dsc_resource '[WindowsFeature]feature' do
    resource :WindowsFeature
    module_name 'PSDesiredStateConfiguration'
    module_version '1.1'
    property :Name, feature
    property :Ensure, 'Present'
    if reboot_pending?
      notifies :reboot_now, 'reboot[Application_Requires_Reboot]', :immediately
    end
end
```

**Comment by coderanger** [comment]
Are you 100% sure you the `reboot_pending?` method was mocked correctly? Otherwise this is a correct test failure.

**Comment by MichaelStankiewicz** [comment]
I never mocked that in my spec before.  But if I need to do that, then why does dropping the 'immediately' property cause this to work without needing to mock reboot_pending?

**Comment by coderanger** [comment]
No idea on that front but I would put some pry or prtinf debugging in your code to check that things are working like think they are in the recipe.

**Comment by MichaelStankiewicz** [comment]
Forgive my ignorance, but what would be the best way to mock 'pending_reboot?'?

**Comment by coderanger** [comment]
Going to close this out as it doesn't seem like a ChefSpec bug at this time. Please re-open if you have more information.
