### ISSUE TITLE
Protect users from Mixlib::ShellOut by default

### ISSUE THREAD

**Issue by atheiman** [chefspec/chefspec#882]
Just like with `if 'command'` and `not_if 'another-command'` guards, Mixlib::ShellOut should probably be stubbed by default to raise an error instructing the user to stub the command.

I think this would make chefspec safer for new users who may be wanting to add chefspec tests for a recipe that calls out to this and then accidentally end up running a potentially dangerous command on their machine.

looks like the change would go here (somehow, this code is not super straightforward to me 😄  ) https://github.com/chefspec/chefspec/blob/master/lib/chefspec/errors.rb

sorta related https://github.com/chefspec/chefspec/issues/264 is an example of a new user wanting to stub out Mixlib::Shellout

**Comment by coderanger** [comment]
I think this is out of scope here, it would get really messy :-/

**Comment by atheiman** [comment]
If anyone finds this issue and wants to do it globally for a cookbook this worked for me in a `spec_helper.rb`:

```ruby
RSpec.configure do |config|
  config.before(:each) do
    # protect user from accidentally running command locally with ShellOut
    allow(Mixlib::ShellOut).to receive(:new).with(any_args) do |obj|
      msg = "Call to Mixlib::ShellOut detected. Executing commands on your machine is not safe!\n" \
        "You can stub this command in a `before` block with something like:\n" \
        "  dbl = double(run_command: nil, stdout: 'expected output')\n" \
        "  allow(Mixlib::ShellOut).to receive(:new).with('#{obj}').and_return(dbl)"
      raise msg
    end
  end
end
```

**Comment by coderanger** [comment]
`allow(Mixlib::ShellOut).to receive(:new).and_raise(<<-EOH)` if want something slightly shorter :)

**Comment by lamont-granquist** [comment]
not opposed to this in principle, but no time.  "PRs accepted".
