### ISSUE TITLE
notify/subscribe to the resource defined somewhere else

### ISSUE THREAD

**Issue by llibicpep** [chefspec/chefspec#885]
Hi,

I have my wrapper-cookbook, where default recipe includes something from opensource, and then includes another recipe from itself. There is a resource in this another recipe that should subscribe to the resource defined in opensource. Here it is:

```
link "..." do
  ...
  subscribes :create, 'service[jenkins]', :before
end
```

Now I am trying to test this recipe:

```
require 'spec_helper'

describe '...' do
  let :solo do
    ChefSpec::SoloRunner.new
  end

  let :chef_run do
    solo.converge(described_recipe) do
      solo.resource_collection.insert(
        Chef::Resource::Service.new('jenkins', solo.run_context))
    end
  end

  context 'configuration' do
    it 'should ...' do
      link = chef_run.link("...")
      expect(link).to subscribe_to('service[jenkins]').on(:create).before
    end
  end
end
```

And I am getting the following error:

```
       expected _something_ to notify "link[...]" with action :create before, but the _something_ you gave me was nil! If you are running a test like:

         expect(_something_).to notify('...')

       Make sure that `_something_` exists, because I got nil
```

It used to work for me in chef-dk 1.5.0. I am trying the latest one and it seems like a regression to me.

```
Chef Development Kit Version: 2.4.17
chef-client version: 13.6.4
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.19.2
inspec version: 1.45.13
```

**Comment by coderanger** [comment]
Manually creating a resource with `.new` like has never been officially been supported, but we definitely broke it even more with Chef 13. You should make a test recipe that includes the `service` resource instead.

**Comment by llibicpep** [comment]
Thanks for the response @coderanger, I knew it's probably unsupported but I found it here https://github.com/chefspec/chefspec/issues/658#issuecomment-181456247, you newer know was it official or another user suggestion.

Is there any plans to simplify this stubbing? I wish it's been as simple as to stub a data bag.

**Comment by coderanger** [comment]
Given that this kind of complex notification chaining is very much not a good way to write Chef recipe code in the first place, it's not super high on my list of things to fix. It is sometimes required, but usually it's a sign of other broken-ness in the deployment tooling or code. The longer term fix for this would be making it easier to define test recipe in-line in a block so you could do something like:

```ruby
describe ... do
  recipe do
    service 'jenkins'
    include_recipe 'thething'
  end
  # ...
end
```

Since that would use the real DSL machinery to create the `service` resource, it would work better.

**Comment by llibicpep** [comment]
I don't really follow what's wrong with restarting a service defined in another open-source cookbook or linking a working dir from external drive for the service before it starts. Complex notification chains is an evil indeed, but sometimes opensource cookbook implementation leaves no other choice for my wrapper than introducing a simple, not chained notification.

**Comment by coderanger** [comment]
Optimally that community cookbook would give you either a resource property or node attribute to set the folder rather than having to use a link in the first place. If this is trying to do stuff for `$JENKINS_HOME`, that is indeed controllable via attribute: https://github.com/chef-cookbooks/jenkins/blob/master/attributes/master.rb#L183

**Comment by llibicpep** [comment]
If the open source cookbook has desired functionality built-in it would not have caused a problem to solve at the first place. I probably dumb but not that much :)

In my case I need `$JENKINS_HOME` untouched, but `$JENKINS_HOME/jobs` to be an external drive. And given several refuses to accept my changes for various reasons such as increasing complexity with the functionality that no one (but me) really need, I thought it would be easier and much faster just to place a notification to my wrapper. But hey ho, I don't really think it worth discussing in this thread :)

**Comment by coderanger** [comment]
Yeah, something like that is getting in to territory I can't handle via ChefSpec. I would also say that given that complexity, good integration tests with Test Kitchen will be worth about a million unit tests :) But for now, if you want to unit test this either don't stub the `include_recipe 'jenkins'` or use a test fixture recipe.

**Comment by llibicpep** [comment]
Thanks, I will do fixture then.

PS: I don't think you can replace unit tests with integration tests, those are simply two different levels with different goals and should co-exist. I have both...

**Comment by coderanger** [comment]
I have words about that over at https://coderanger.net/overtesting/

You probably don't need both.

**Comment by llibicpep** [comment]
@coderanger that was interesting reading, thanks, and I'm happy to see that community has recognized yet another pattern. Though I agree what you say is true for most of the cases, I would disagree that 100% coverage is *always* a bad sign. I do hope that nowdays we as a community finally recognized another pattern as well - there are no silver bullets and statements that works in 100% cases.

Particularly I do believe that 100% code coverage on different levels would save a day in the environment where >5k people are actively collaborating on a huge codebase where most of collaborators are unfamiliar with it. This would be true for most of big companies doing DevOps culture and as so letting their java/ruby/python/php/etc product developers help themselves with unfamiliar for them Chef in-house cookbooks. In that case the extensive tests coverage together with a delivery platform that isolating deployment risks and doing quality gateways would definitely enable the process in a pro-active rather than re-active way, save time on a code reviews and save a lot of legs from the bullets. For me the ability to do test coverage and all that cool toolset coming out of the box is one of the most important benefits of doing configuration as a code over traditional automation scripts.

On the other hand the companies with such a head count can't hire superstars only. If not the budget, there are simply no that many superstars available on the market. I would suggest to think about BDD instead of traditional unit testing (which I think rspec/chefspec already doing great). Usually you are able to examine a code diff in your PR, but what if the platform you are doing a change to is unfamiliar ground to you, because you are not [yet] superstar or it's simply not a your field? The unit tests (or better behavior tests) would show you pretty much the same diff but from the behavior point of view, so you are not required to be experienced to catch up all the consequences that sometimes can be not that obvious.

Not to mention that the unit tests sometimes is a perfect place for some code documentation and/or low level technical decision logs.

Maintaining such a coverage is way too expensive, indeed. But yet this cost sound reasonable to me given a huge head count I am working with, but indeed there are areas for improvements. And there are already a lot of progress around, such as JS Cucumber approach https://www.sitepoint.com/bdd-javascript-cucumber-gherkin/ which sounded pretty much like we can soon enough automate the process by producing the tests automatically right from the user story acceptance criteria. Backend guys are pretty close to streamline documentation-driven backend production, such as the tests automatically produced from the reference API docs such as Swagger https://www.npmjs.com/package/swagger-t-str. And finally I think that the day for automatic unit/behavior tests generating is not far away, we do have static code analysis for ages already - at some point we should be able to capture behavior pattern from our code, and then alert code changes on it's unexpected behavior changes.

**Comment by szymonpk** [comment]
Maybe someone will find this useful, I have managed to figure out what changed between ChefSpec 6 and 7.

[find_resource now verifies declared_type](https://github.com/chefspec/chefspec/blob/9962e993039e185764c836f23dc337d58310f85e/lib/chefspec/solo_runner.rb#L180), so when you are injecting resource you have to set it explicitly. Based on @llibicpep code, it should be:

    let :chef_run do
      mocked_resource = Chef::Resource::Service.new('jenkins', solo.run_context))
      mocked_resource.declared_type = :service
  
      solo.converge(described_recipe) do
        solo.resource_collection.insert(mocked_resource)        
      end
    end

It is ugly as hell, use on your own responsibility.
