### ISSUE TITLE
Looping in chefspec.

### ISSUE THREAD

**Issue by avinashgaonkar** [chefspec/chefspec#890]
Hi All,
I am getting and error for my chefspec when using a command to cat a file /etc/passwd it says "cat: /etc/passwd: No such file or directory"
below is my recipe and the spec unit test associated with it,...let me know if i am doing something wrong here..

**recipe:** 
names = `cat /etc/passwd|cut -d: -f6`
names_ar = names.split(' ')
names_ar.each do |i|
  execute "Check for file .shosts in directory #{i}" do
    command "find #{i} -type f -name .shosts | xargs /bin/rm -f 2>/dev/null"
    not_if "find #{i} -type f -name .shosts |wc -l|egrep '^0$'"
  end
end
#####################
**xyz_spec.rb:**

require 'spec_helper'

describe 'xyz::SET-1234' do
  before do
    names = `cat /etc/passwd|cut -d: -f6`
    names_ar = names.split(' ')
    names_ar.each do |i|
      stub_command("find #{i} -type f -name .shosts |wc -l|egrep '^0$'").and_return(false)
    end
  end
.
.
.
.
.
            let(:chef_run) do
              ChefSpec::SoloRunner.new(platform: platform, version: version) do |node|
                # Node attributes
              end.converge(described_recipe)
            end

            it 'converges successfully' do
              names = `cat /etc/passwd|cut -d: -f6`
              names_ar = names.split(' ')
              names_ar.each do |i|
                expect { chef_run }.to_not raise_error
                expect(chef_run).to run_execute("Check for file .shosts in directory #{i}")
              end

Thanks for your help.

**Comment by coderanger** [comment]
Answered on Slack, this is not a ChefSpec bug.
