### ISSUE TITLE
fauxhai version constraint

### ISSUE THREAD

**Issue by limitusus** [chefspec/chefspec#895]
https://github.com/chefspec/chefspec/blob/master/chefspec.gemspec#L29
has constraint fauxhai < 6.

On the other side fauxhai released v6.0.1.
https://github.com/chefspec/fauxhai/releases

I'd be happy if you can loosen the version constraint, as I faced an issue the latest installed fauxhai is not used by chefspec.

**Comment by coderanger** [comment]
As with many chef ecosystem projects, the supported way to install ChefSpef is via the ChefDK packages. As such, we do upgrade work in batches since we expect to have some time before it all gets released. This will be be fixed up before the ChefDK 3 release in April.
