### ISSUE TITLE
How do I run an older version of ChefSpec, or otherwise test against a specific version of Chef?

### ISSUE THREAD

**Issue by RulerOf** [chefspec/chefspec#898]
I'm trying to test my recipes against the latest Chef 12 release, but ever since I updated to the latest ChefDK, ChefSpec runs its tests against a newer version that my cookbooks do not support, as shown by the System Info dumped at the end of the error I get now:

```
11:51 $ chef exec rspec

bq-core::awscli
  On centos 6.8, without Vagrant without existing CLI installation

================================================================================
Recipe Compile Error in /var/folders/_r/fkl_5h650sx8lb4jjlpm1zzr0000gn/T/d20180426-33413-vrc9av/cookbooks/git/libraries/z_provider_mapping.rb
================================================================================

NoMethodError
-------------
undefined method `set' for Chef::Platform:Class
Did you mean?  send

Cookbook Trace:
---------------
  /var/folders/_r/fkl_5h650sx8lb4jjlpm1zzr0000gn/T/d20180426-33413-vrc9av/cookbooks/git/libraries/z_provider_mapping.rb:6:in `<top (required)>'

Relevant File Content:
----------------------
/var/folders/_r/fkl_5h650sx8lb4jjlpm1zzr0000gn/T/d20180426-33413-vrc9av/cookbooks/git/libraries/z_provider_mapping.rb:

  1:  # provider mappings for Chef 11
  2:  
  3:  #########
  4:  # client
  5:  #########
  6>> Chef::Platform.set platform: :amazon, resource: :git_client, provider: Chef::Provider::GitClient::Package
  7:  Chef::Platform.set platform: :centos, resource: :git_client, provider: Chef::Provider::GitClient::Package
  8:  Chef::Platform.set platform: :debian, resource: :git_client, provider: Chef::Provider::GitClient::Package
  9:  Chef::Platform.set platform: :fedora, resource: :git_client, provider: Chef::Provider::GitClient::Package
 10:  Chef::Platform.set platform: :mac_os_x, resource: :git_client, provider: Chef::Provider::GitClient::Osx
 11:  Chef::Platform.set platform: :redhat, resource: :git_client, provider: Chef::Provider::GitClient::Package
 12:  Chef::Platform.set platform: :scientific, resource: :git_client, provider: Chef::Provider::GitClient::Package
 13:  Chef::Platform.set platform: :smartos, resource: :git_client, provider: Chef::Provider::GitClient::Package
 14:  Chef::Platform.set platform: :solaris2, resource: :git_client, provider: Chef::Provider::GitClient::Package
 15:  Chef::Platform.set platform: :suse, resource: :git_client, provider: Chef::Provider::GitClient::Package

System Info:
------------
chef_version=13.8.5
platform=centos
platform_version=6.8
ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin14]
program_name=/opt/chefdk/embedded/bin/rspec
executable=/opt/chefdk/embedded/bin/rspec

    should install the packages (FAILED - 1)
```

The readme says that the versions you test against are generally supported, and the latest Travis runs show a passing test for a recent version of Chef 12. Travis appears to set the `CHEF_VERSION` environment variable to get that to work, but that doesn't change the behavior at all for me.

Does anyone have any suggestions on how I could accomplish this? If there's been some kind of oversight with this not being covered in existing documentation, I'd be happy to contribute. 

Thanks.

**Comment by coderanger** [comment]
The version of Chef that you test against when using ChefSpec is the version of the Chef gem that is installed. This is generally determined by the version of ChefDK that you install. There is no (non-awful) way to get newer ChefDK but test against older Chef.

**Comment by lamont-granquist** [comment]
bundle with chefspec and the old version of chef and `bundle exec rspec`.

we don't appbundle chefspec/rspec in chefdk so there's no issue one way or the other there with appbundle pins.  so chefspec simply pulls down the latest version of chef it finds.  since chefdk will be pulling in a later version, i think the only solution is to bundle with a Gemfile to lock to a lower version.

**Comment by RulerOf** [comment]
My cookbook's `Gemfile` went from an extremely long one that I wasn't really using (i.e. I never actually ran bundler as part of normal cookbook development) down to a minimalist one consisting of only the bare minimum that was required to get ChefSpec to function:

```ruby
source 'https://rubygems.org'

gem 'chef', "~> 12"
gem 'chefspec'
gem 'berkshelf'
```

After that, a `bundle install` and `bundle exec rspec` were all that was necessary to run my ChefSpec tests the way I needed to, just as @lamont-granquist suggested, and it doesn't seem to have broken anything else in my dev/test pipeline.  Thanks!
