### ISSUE TITLE
ChefSpec's coverage reporting is deprecated and will be removed in a future version

### ISSUE THREAD

**Issue by y0y0z** [chefspec/chefspec#899]
when i run chefspec 7.2.0, i get the deprecation message

> ChefSpec's coverage reporting is deprecated and will be removed in a future version

i am [aware of the deprecation][1].
i really love the coverage report. is there any alternative for chef cookbook coverage?

[1]: https://github.com/chefspec/chefspec#reporting

**Comment by coderanger** [comment]
No, there is no alternative or replacement for cookbooks. The feature was structurally problematic and resulted in bad incentives. We apologize for the trouble.
