### ISSUE TITLE
Testing multiple templates into same destination isn't captured correctly

### ISSUE THREAD

**Issue by mik047** [chefspec/chefspec#900]
Hi,

I am new to ruby and chef. So apologies in advance in case I have not understood things correctly or providing insufficient information below. 

 Coming to the problem, context is: I have written a custom resource, say xyz, which essentially copies two template files into the same directory. The relevant code (within the action implementation) looks like as follows.

```
[
      ["a_file.erb", '0600'],
      ["another_file.erb", '0644']
  ].each {|source_erb, mode_erb|
    template location do
      source source_erb
      owner 'abc'
      group 'pqr'
      mode mode_erb
    end
  }
```
And, to test this, I am using following code:

```
[
        ['a_file.erb', '0600'],
        ['another_file.erb', '0644']
    ].each {|source_erb, mode_erb|
      it 'creates two files' do
        expect(chef_run).to create_template(location).with(
            source: source_erb,
            owner: 'abc',
            group: 'pqr',
            mode: mode_erb)
      end
    }
``` 

Please assume that the variables like 'location' etc. are appropriately initialised. 

When I run ChefSpec, it complains on the following lines.

> expected "template[location]" to have parameters:
> 
>  source "a_file.erb", was "another_file.erb"
>  mode "0600", was "0644"
> ....

What I have noticed is, chef-spec is only recording the last execution of the template resource (even though both template resource are being executed). Meaning, in the given code, it only notices template resource execution for 'another_file'. And hence, test for 'a_file' always fails.

If I switch the order (of the files), the test always passes for 'a_file' and always fails for 'another_file'.

Can we please take care of this (or enlighten me in case I am doing anything wrong?)

ps : please let me know in case I have not provided enough details.

**Comment by coderanger** [comment]
What would you expect this to actually do? The second template will totally overwrite the first. Which is what the test is telling you.

**Comment by coderanger** [comment]
Perhaps you are guessing that if you give the `template` resource a directory path rather than a file path, it will somehow work out which file to write to? If so, it will not.

**Comment by mik047** [comment]
Ouch!.... My bad! ..... Thanks @coderanger for the explanation and directing me correctly. It works now. :)
