### ISSUE TITLE
undefined method `sysctl' for cookbook

### ISSUE THREAD

**Issue by tomasz-bres** [chefspec/chefspec#901]
I'm using `sysctl `resource in my cookbook: https://docs.chef.io/resource_sysctl.html
There's no problems with converging kitchen, however `chef exec rspec` is failing with:
```
NoMethodError:
        undefined method `sysctl' for cookbook
```
I'm using latest chefdk:
```
$ chef -v
Chef Development Kit Version: 2.5.3
chef-client version: 13.8.5
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.20.0
inspec version: 1.51.21
```

**Comment by lamont-granquist** [comment]
That docs page specifies "New in Chef Client 14.0." which means it won't be in the chef 13.8.5 which is in that version of the ChefDK.  That behavior is correct.
