### ISSUE TITLE
Cookbook not uploading due to error with spec file

### ISSUE THREAD

**Issue by joshk132** [chefspec/chefspec#913]
I am trying to upload a cookbook called 'cookbookABC' and it has the following chef spec code but I am not sure why it is failing:

let(:tool_path) { '/wk/wildfly_tools' }
      %w(/tailLog.sh' /tailLog.sh /clearTmpData.sh /clearOldServerLog.sh /startJBoss.sh /jboss_standalone_start.sh).each do |path|
        expect(chef_run).to create_template(['tool_path']+ path).with(
          owner: useradmin
          group: useradmin
          mode: '0744'
        )
      end

It is telling me I have a syntax error. I have narrowed it down to being related to the `%w(/file /file2)` section.

**Comment by coderanger** [comment]
Please include the specific error output you are getting.

**Comment by lamont-granquist** [comment]
this is not a bug against chefspec, this is a better question for stackoverflow, discource or slack.
