### ISSUE TITLE
ChefSpec not loading definition files during SoloRunner convergence

### ISSUE THREAD

**Issue by miroswan** [chefspec/chefspec#926]
Version: 7.3.1

Exceptions thrown here whenever there is a cookbook in a run_list under solo runner convergence that  uses a definition. This is the line where things breakdown: https://github.com/chef/chef/blob/master/lib/chef/dsl/definitions.rb#L31

The previous line returns nil:

```
new_def = run_context.definitions[definition_name].dup
```

So when the subsequent line calls params on new_def, a no method error is raised on nil. This is because the Hash under run_context.definitions is empty. I used pry to discover that definition files were not getting loaded. 

I haven't dug deep enough to determine what changed between ChefSpec version 7.2.1 and 7.3.1, but it's working in the former and not the latter.

**Comment by coderanger** [comment]
There is a roughly 0% chance I'll fix this. Sorry. Definitions have been deprecated for years, you need to fix your code or not use ChefSpec.

**Comment by rmcleod8** [comment]
If definitions are truly deprecated, the chef docs should reflect that. https://docs.chef.io/definitions.html# states they are not actually deprecated. Not sure who should make that call/update to docs

**Comment by Poohblah** [comment]
Agreed.  Definitions are explictly not deprecated.  From the docs:

> While definitions is not deprecated—all existing definitions will continue to work...

**Comment by robbkidd** [comment]
The [Chef docs](https://github.com/chef/chef-web-docs) are a better place to make commentary about what the docs should say. Open an issue or a PRs making the desired update. There's an `[edit on GitHub]` link at the top of every page to make it easy to offer content suggestions and corrections.

**Comment by Poohblah** [comment]
@robbkidd We can't suggest an update to the docs or open a PR because there's conflicting information from Chef about whether definitions are deprecated, so we don't know what the docs should say.

**Comment by tas50** [comment]
Definitions aren't deprecated, but they are HIGHLY discouraged. I've opened a PR to the docs site that spells that out more bluntly. Many things have never worked with definitions and never will. Existing definitions should 100% be converted to custom resources. We're not intending to remove the code that powers definitions from Chef *yet*, but that will happen sometime in the future. We've been flagging definitions with Foodcritic for 4 or 5 years now and recommending folks rewrite them.

**Comment by Poohblah** [comment]
That's too bad, because some things still only work with definitions but don't work with custom resources.  For instance, [resources that use the accumulator pattern, such as `firewall_rule` from the official firewall cookbook, work inside of definitions but not custom resources](https://github.com/chef-cookbooks/firewall/issues/212).  We haven't been able to migrate some of our definitions to custom resources because of this.
