### ISSUE TITLE
how to control bash resource return

### ISSUE THREAD

**Issue by estein9825** [chefspec/chefspec#928]
I want to test the behavior when I execute a bash resource. I would like it to return 0 sometimes and 1 other times. Unfortunately, I can't seem to figure out whether I need to create a stub_command or allow_any_instance_of or something else to do it. I've tried both without any luck.

```
stub_command(/service postgresql restart.*/).and_return(1)
```
And also
```
allow_any_instance_of(Chef::Resource::Bash).to receive(:run).with(my_bash_file).and_return(1)
```

Has anyone successfully done this before?

**Comment by coderanger** [comment]
Resources don't return anything. When they error, it fails the run. We don't generally bother checking for that as it's a core feature of Chef and irrelevant for unit testing.

**Comment by estein9825** [comment]
Yeah, I decided to add a test in the front end of the chef recipe, so I'm thinking it's not needed anyway. Thanks.
