### ISSUE TITLE
Custom resources with more than one action will not execute correctly in recipe block

### ISSUE THREAD

**Issue by martinisoft** [chefspec/chefspec#945]
Given a custom resource with more than one action:

```ruby
action :install do
  log 'install'
end

action :create do
  log 'create'
end
```

Given a spec with the following:

```ruby
describe 'myresource' do
  step_into :myresource
  recipe do
    myresource 'test' do
      action :create
    end
  end
  it { is_expected.to write_log('create') }
end
```

It will fail to find the log resource named 'create' in the run collection.

**Comment by martinisoft** [comment]
For more context, I commented out the case where I originally found this here: https://github.com/sous-chefs/postgresql/pull/585/commits/4e83526a81cbbdc90057f582d93de7d855bd10e6#diff-c68d5bb19fb07731b5747bcbcf8f83bbR54

**Comment by coderanger** [comment]
I mean there are clearly a lot of core resources with more than one action, so I suspect you have not accurately tracked down the issue :) Is either action running? Read: is this an issue with step_into or with the matcher system

**Comment by coderanger** [comment]
Closing as invalid, misunderstanding of how and when to use `step_into`.
