### ISSUE TITLE
windows_task fails converge test on MacOS

### ISSUE THREAD

**Issue by bwhitacrejha** [chefspec/chefspec#952]
Chef Workstation v0.2.48
chefspec v7.3.4
rspec v3.8.0

I have tested this from Chef Workstation v0.2.48 on both:

- Windows 10 Enterprise
- Mac OS Mojave

Using windows_task resource in a recipe to create a simple task:
```
windows_task 'Chef_Initial_OnBoot' do
  command 'cmd /c c:/opscode/chef/bin/chef-client'
  frequency :onstart
  run_level :highest
end
```

Recipe works fine, does what is expected.  Both in Test Kitchen and in Production.

Using default Chefspec test:
```
context 'When all attributes are default, on Windows 2016' do
  let(:chef_run) do
    runner = ChefSpec::ServerRunner.new(platform: 'windows', version: '2016')
    runner.converge(described_recipe)
  end
  it 'converges successfully' do
     expect { chef_run }.to_not raise_error
  end
end
```

- Windows 10 workstation - test passes fine. 
- MacOS Mojave workstation - test fails. `expected` no Exception, got #<Chef::Exceptions::ValidationFailed: Property user must be one of: String!  You passed nil.> with backtrace:`

I have tried multiple actions for the windows_task resource and the result in ChefSpec is still the same. 
I have tried using both SoloRunner and ServerRunner.

Appears ChefSpec on MacOS when exercising the windows_task resource in the mock run is not loading the default user of SYSTEM.

**Comment by tas50** [comment]
This is mostly due to how we handle this under the hood in Chef. Let me think about how we'd want to go about fixing it.

**Comment by claudiuion** [comment]
Hello, 
I have a similar issue on Linux (Debian 10).
recipe:
```
windows_task 'application' do
  user 'SYSTEM'
  command "#{binary_path}\\application.cmd"
  frequency :minute
  frequency_modifier 1
  action :create
end
```
spec_helper:
```
# frozen_string_literal: true

require 'chefspec'
require 'chefspec/berkshelf'

RSpec.configure do |config|
  config.color = true               # Use color in STDOUT
  config.formatter = :documentation # Use the specified formatter
  config.log_level = :error         # Avoid deprecation notice SPAM
  config.platform = 'windows'
  config.version = '2016'
  config.file_cache_path = '/tmp/chef/cache'
end
```
test:
```
require 'spec_helper'

describe 'services::application' do
  context 'When all attributes are default' do
    let(:chef_run) do
      runner = ChefSpec::ServerRunner.new do |node, server|
        server.create_data_bag('admins',
                               'Admin' => {
                                 id: 'Admin',
                                 password: 'P@ssw0rd'
                               })
        server.create_data_bag('users',
                               'User' => {
                                 id: 'User',
                                 password: 'P@ssw0rd'
                               })
        node.normal['services']['program_data'] = 'C:\\ProgramData\\application'
        node.normal['services']['program_files'] = 'C:\\Program Files\\application'
      end
      runner.converge(described_recipe)
    end

    it 'converges successfully' do
      expect { chef_run }.to_not raise_error
    end
```
 The error is:
```
Failures:

  1) services::application When all attributes are default converges successfully
     Failure/Error: expect { chef_run }.to_not raise_error
     
       expected no Exception, got #<NameError: uninitialized constant Chef::ReservedNames::Win32::Security
```

**Comment by coderanger** [comment]
@claudiuion That is unrelated, you cannot use most of the Windows resources on non-Windows platforms, even in unit tests. You'll have to run your unit tests on Windows.

**Comment by shanechaplain** [comment]
I am seeing the exact same error as @bwhitacrejha in our pipeline on Cent7.

**Comment by shanechaplain** [comment]
I am seeing the same error in our CI/CD pipeline running on Centos7

Chef Workstation: 0.2.53
chefspec (7.3.4)
rspec (3.8.0)


Resource
```
windows_task 'Delete Scheduled Task to Re-Attempt the Chef-Client Upgrade Daily' do
  task_name 'chef_upgrade_daily'
  action :delete
end
```

This is the chefspec

```
require 'spec_helper'

describe 'chef_client::upgrade_chef_client' do
  context 'When attributes default, on Windows 2016' do
    let(:chef_run) do
      runner = ChefSpec::SoloRunner.new(platform: 'windows', version: '2016')
      runner.converge(described_recipe)
    end

    it 'converges successfully' do
      expect { chef_run }.to_not raise_error
    end
  end
end
```

This passes on Windows, fails on Centos7

**Comment by coderanger** [comment]
@shanechaplain Same answer, to unit test Chef on Windows, you must run the unit tests on Windows.

**Comment by palfrey** [comment]
I've been able to workaround this with the following
```
    stubs_for_resource('windows_task') do |res|
      allow(res).to receive(:validate_user_and_password).and_return(nil)
    end
```

**Comment by riccalioliojr** [comment]
@palfrey Where exactly did you write the stubs? TIA

**Comment by riccalioliojr** [comment]
Using `:validate_user_and_password` in the stub does not work for me. This worked for me:

```
stubs_for_resource('windows_task') do |res|
    allow(res).to receive(:user).and_return(nil)
end
```

Either as a `before` block or inside the `it` block, right before the `expect` line.

**Comment by tas50** [comment]
Like @coderanger said it's very difficult to unit test windows resources on a non-windows system. There are potentially a dozen win32 Ruby gems that get loaded when you use one of these resources and due to how those are designed they can't be loaded on non-windows hosts. This means you're going to be mocking out a HUGE amount of code and any internal refactoring to chef may break all of that for no understandable reason. I'm going to close this since it's beyond our control to fix it. Additionall InSpec is what you really want here since you probably care about the task actually being created vs. you just telling chef to create it.
