### ISSUE TITLE
Make PolicyFile Path (and name of file) Configurable

### ISSUE THREAD

**Issue by gscho** [chefspec/chefspec#956]
I have a bunch of cookbooks wrapped up in a habitat package that share a policyfile. I'd like to implement some chefspec tests inside these cookbooks so that they can be run inside a build phase callback when building the hab package.

Currently I don't see a way to configure this path. Looks to be [hard-coded](https://github.com/chefspec/chefspec/blob/ac4bc68b5cd97241af53bd24da90d06708e570fb/lib/chefspec/policyfile.rb#L25) to `policyfile_path = File.join(Dir.pwd, 'Policyfile.rb')`.

**Comment by ehvidal** [comment]
This feature would be so useful! Without having this it is really hard to have different policyfiles associated to a cookbook. Thank you very much for working on this!
