### ISSUE TITLE
Mock node.run_state

### ISSUE THREAD

**Issue by MattBraden** [chefspec/chefspec#976]
Hey!

I am trying to write a test for a custom resource I created.  The custom resource uses the run_state to track which packages have been installed and removed during a chef run.

Snip from custom resource: up_package.rb
```
$stdout.puts "Before: #{node.run_state}"
if node.run_state['package_install_remove'] == nil
  node.run_state['package_install_remove'] = []
end
$stdout.puts "After: #{node.run_state}"
```

Snip from up_package_spec.rb
```
context 'Fails if package has already been installed/removed this chef run' do
  $stdout.puts "Running test: #{test_resource} #{self.description}"
  # Mock the chef run node data
  before do
    chef_run.node.run_state["package_install_remove"] = [{ :name => "UPPython-2.7" }]
  end

  recipe do
    up_package 'install' do
      name 'UPPython-2.7'
      version '2.7.9'
      release '1.el6'
      arch 'x86_64'
      os ['6']
      action :install
    end
  end

  it do
    is_expected.to raise_error
  end
end
```

Snip of `chef exec rspec`
```
Running test: up_package Fails if package has already been installed/removed this chef run
Before: {}
After: {"package_install_remove"=>[]}
F

Failures:

  1) up_package Fails if package has already been installed/removed this chef run is expected to raise Exception
     Failure/Error: is_expected.to raise_error
       expected Exception but was not given a block
     # ./spec/up_package_spec.rb:74:in `block (3 levels) in <top (required)>'

Finished in 13.49 seconds (files took 3.66 seconds to load)
```

Does anyone know how I can mock out the node.run_state data properly?

Thanks!

**Comment by petracvv** [comment]
I think I just figured this out after struggling myself in a similar situation.

You can't mock the run state using `chef_run` because that represents an already completed run of Chef in chefspec so your resources already executed without the mock.

However you can mock it using the `chef_runner` object that represents the chef run before it converges.

So you can do:
```
before do
    chef_runner.node.run_state["package_install_remove"] = [{ :name => "UPPython-2.7" }]
end
```

Try that out and see if it works for you. I was able to get my tests working with the above.

**Comment by mattlqx** [comment]
Thank you for making this easy to find. It would be nice if this was added to the README.
