### ISSUE TITLE
Notifications from inside ruby_block not correctly linked to the outside resource

### ISSUE THREAD

**Issue by ci** [chefspec/chefspec#982]
Example resource:

```
ruby_block 'restart services' do
  block do
    notifies :restart, "service[svc]" if should_notify?('svc')
  end
  action :nothing
end
```

Testing this using:

```
let(:ruby_block) { chef_run.ruby_block('restart services') }

it 'ruby_block triggers notifications' do
  ruby_block.block.call

  expect(ruby_block).to notify('service[svc]').to(:restart)
  # using an allow before, and testing using this works:
  # expect(ruby_block).to have_received(:notifies).with(:restart, 'service[svc]')
end
```

Doesn't work at first, throwing an odd error:

```
Failure/Error: expect(ruby_block).to notify('service[svc]').to(:restart)

NoMethodError:
  undefined method `name' for "service[svc]":String
# ~/gems/chefspec-7.1.1/lib/chefspec/matchers/notifications_matcher.rb:135:in `format_notification'
# ~/gems/chefspec-7.1.1/lib/chefspec/matchers/notifications_matcher.rb:141:in `block in format_notifications'
# ~/gems/chefspec-7.1.1/lib/chefspec/matchers/notifications_matcher.rb:140:in `map'
# ~/gems/chefspec-7.1.1/lib/chefspec/matchers/notifications_matcher.rb:140:in `format_notifications'
# ~/gems/chefspec-7.1.1/lib/chefspec/matchers/notifications_matcher.rb:73:in `failure_message'
# ./spec/chef/spec.rb:5:in `block (4 levels) in <top (required)>'
```

This hints at that the resource (`service[svc]`) is not correctly converted to Chef::Resource, but a String. Adding extra logging to `lib/chefspec/matchers/notifications_matcher.rb` - [the resource is a string](https://github.com/chefspec/chefspec/blob/d6e7c0f28bdd696a2c4a80f1c954472d85a3d6b3/lib/chefspec/matchers/notifications_matcher.rb#L15) whereas moving the notifies to the `ruby_block` resource level (instead of inside the block) correctly converts it to the resource.

P.S: this scenario seems to be [working and tested in the Chef codebase](https://github.com/chef/chef/blob/bec29232c2b42609a4746f4df9141758af87287f/spec/functional/notifications_spec.rb#L198-L227).

**Comment by lamont-granquist** [comment]
that syntax is incorrect.  the example in the chef codebase wraps the notifies in a log resource.

that is also going to be deeply weird to test in chefspec and pretty much unsupported.  we test we didn't break that, but defining resources within a ruby_block is ultimately going to wind up being so confusing that i'm likely the only person in the world who will be able to explain why it is necessarily confusing, and i don't scale.  please don't do that.
