### ISSUE TITLE
NoMethodError thrown for custom resources that reference node attributes as defaults 

### ISSUE THREAD

**Issue by mattlqx** [chefspec/chefspec#985]
I spent a while tracking this one down. This manifests itself similarly to #953 in that the ChefSpec test will fail with a NoMethodError but the reason is different. I have a cookbook that depends on the [telegraf](https://github.com/NorthPage/telegraf-cookbook) cookbook. The telegraf cookbook provides custom resources that non-lazily specify defaults based on a node attribute (`node['telegraf']['config_file_path']`). This attribute has a default defined in the cookbooks `attributes/default.rb` and it works out fine in actual chef-client. But something, and I'm not sure what, is different with how ChefSpec loads cookbook's attribute and/or resource files.

Take the resource `telegraph_inputs` for example. This [line](https://github.com/NorthPage/telegraf-cookbook/blob/0.12.0/resources/inputs.rb#L21) for the `path` property.

`property :path, String, default: ::File.dirname(node['telegraf']['config_file_path']) + '/telegraf.d'`

When ChefSpec'ing a recipe that uses this resource, it will throw the following error:

```
NoMethodError
-------------
undefined method `telegraf_inputs' for cookbook: mycookbook, recipe: myrecipe :Chef::Recipe
```

I threw a log line in the telegraf cookbook's attributes/default.rb to show that the attribute file is processed and the attribute has a value:

```
[2020-04-29T09:02:03-07:00] DEBUG: Node fauxhai.local loading cookbook telegraf's attribute file /var/folders/6l/jbm1dx7j565_gmwy0xcm4r7c0000gn/T/d20200429-63036-1ejqtdl/cookbooks/telegraf/attributes/default.rb
[2020-04-29T09:02:03-07:00] TRACE: Loading Attribute telegraf::default
[2020-04-29T09:02:03-07:00] WARN: config_file_path is /etc/telegraf/telegraf.conf
```

I'm not sure where the disconnect is, but if you wrap the usage of the attribute for the default with a lazy block, everything works as you would expect.

`property :path, String, default: lazy { ::File.dirname(node['telegraf']['config_file_path']) + '/telegraf.d' }`

This definitely seems like a bug with ChefSpec itself, particularly how the actual failure you get doesn't give you any clues as to what the real problem is.

**Comment by tas50** [comment]
We have a cookstyle rule to make sure the node attributes are wrapped in lazy blocks. You really want to do this beyond just ChefSpec. This isn't something to fix on the ChefSpec side. It's just about writing the cookbooks in a way that the code is analyzed at the right time.
