### ISSUE TITLE
Windows service run_as_user attribute is downcased in chef spec matcher

### ISSUE THREAD

**Issue by dave-q** [chefspec/chefspec#999]
I have a resource in a cookbook

```
windows_service 'my service' do
  action :configure
  run_as_user 'NT AUTHORITY\\NetworkService'
end
```

I then had a basic chef spec test

```
it 'configures the windows service to run as the network service account' do
  expect(chef_run).to configure_windows_service('my service')
    .with(run_as_user: 'NT AUTHORITY\\NetworkService')
end
```

This fails with

```
expected "windows_service[my service]" to have parameters:
     
         run_as_user "NT AUTHORITY\\NetworkService", was "nt authority\\networkservice"

```

For some reason the it has downcased the run_as_user value

Rspec version: 
RSpec 3.8
  - rspec-core 3.8.2
  - rspec-expectations 3.8.6
  - rspec-mocks 3.8.2
  - rspec-support 3.8.3

**Comment by dwmarshall** [comment]
Not a bug, recommending to be closed. See https://github.com/chef/chef/blob/25c039a140c3dd8b05ab81b467b36642fc3724c2/lib/chef/resource/windows_service.rb#L227-L230 where `run_as_user` is downcased by the resource itself.

**Comment by lamont-granquist** [comment]
yeah chefspec can't do anything about that, the windows_service resource shouldn't be mutating the new_resource (no resource should ever mutate the new_resource, it causes bugs more or less exactly like this)

**Comment by lamont-granquist** [comment]
oh yeah, that's coercions though in the property, there's other bugs in chefspec open about that though, its endemic.
